################################################
# Make file generated by HEW
#

############################
# Toolchain directory define
# If incorrect, change to the location of the Renesas M32R Standard Toolchain toolchain
TC_INSTALL_DIR = C:\Renesas\cc32r\v501r01

#####################################################
#
# Details:
#   Project: ShiftLight
#   Configuration: Debug
#   Toolchain: Renesas M32R Standard Toolchain
#
#####################################################

################
# Main Defines

# Renesas M32R C Compiler01 phase

SHIFTLIGHT_DEBUG_M32R_C_COMPILER01_EXE=cc32r.exe
SHIFTLIGHT_DEBUG_M32R_C_COMPILER01_EXEDIR=$(TC_INSTALL_DIR)\bin32r
SHIFTLIGHT_DEBUG_M32R_C_COMPILER01_OUTFILESC0="..\ShiftLight\Debug\ShiftLight.mo"

# Renesas M32R Assembler02 phase

SHIFTLIGHT_DEBUG_M32R_ASSEMBLER02_EXE=as32r.exe
SHIFTLIGHT_DEBUG_M32R_ASSEMBLER02_OUTFILESC0="..\ShiftLight\Debug\start.mo"

# Renesas M32R Linker03 phase

SHIFTLIGHT_DEBUG_M32R_LINKER03_INFILESC0="..\ShiftLight\Debug\start.mo" "..\ShiftLight\Debug\ShiftLight.mo"
SHIFTLIGHT_DEBUG_M32R_LINKER03_OUTFILESC0="..\ShiftLight\Debug\ShiftLight.abs"

# Renesas M32R Stype Converter04 phase

SHIFTLIGHT_DEBUG_M32R_LOAD_MODULE_CONVERTER04_EXE=lmc32r.exe
SHIFTLIGHT_DEBUG_M32R_LOAD_MODULE_CONVERTER04_OUTFILESC0="..\ShiftLight\Debug\ShiftLight.mot"

#######################
# nmake "all" statement

ALL:	SHIFTLIGHT_DEBUG_M32R_C_COMPILER01_ENVC0 \
	$(SHIFTLIGHT_DEBUG_M32R_C_COMPILER01_OUTFILESC0) \
	$(SHIFTLIGHT_DEBUG_M32R_ASSEMBLER02_OUTFILESC0) \
	$(SHIFTLIGHT_DEBUG_M32R_LINKER03_OUTFILESC0) \
	$(SHIFTLIGHT_DEBUG_M32R_LOAD_MODULE_CONVERTER04_OUTFILESC0)

####################
# Description blocks

!MESSAGE
!MESSAGE Executing Renesas M32R C Compiler01 phase
!MESSAGE

SHIFTLIGHT_DEBUG_M32R_C_COMPILER01_ENVC0 : 
	set INC32R=$(TC_INSTALL_DIR)\inc32r
	set M32RLIB=$(TC_INSTALL_DIR)\lib32r
	set M32RTMP=$(TC_INSTALL_DIR)\TMP
	set PATH=$(TC_INSTALL_DIR)\bin32r;$(TC_INSTALL_DIR)\bin
	set M32RBIN=$(TC_INSTALL_DIR)\bin32r
	set LIB32R=$(TC_INSTALL_DIR)\lib32r
	set M32RINC=$(TC_INSTALL_DIR)\inc32r

$(SHIFTLIGHT_DEBUG_M32R_C_COMPILER01_OUTFILESC0) : "..\ShiftLight\ShiftLight.c"
	$(SHIFTLIGHT_DEBUG_M32R_C_COMPILER01_EXE) @<<
-cs 
-g 
-o ..\ShiftLight\Debug\ShiftLight.mo 
-O1 
-small 
-lang=c 
..\ShiftLight\ShiftLight.c
<<

!MESSAGE
!MESSAGE Executing Renesas M32R Assembler02 phase
!MESSAGE

$(SHIFTLIGHT_DEBUG_M32R_ASSEMBLER02_OUTFILESC0) : "..\ShiftLight\start.ms"
	$(SHIFTLIGHT_DEBUG_M32R_ASSEMBLER02_EXE) @<<
-D __STANDARD_IO__=0 
-D __HEAPSIZE__=H'4000 
-D __USTACKSIZE__=H'1000 
-D __ISTACKSIZE__=H'1000 
-g 
-l ..\ShiftLight\Debug\start.lst 
-o ..\ShiftLight\Debug\start.mo 
..\ShiftLight\start.ms
<<

!MESSAGE
!MESSAGE Executing Renesas M32R Linker03 phase
!MESSAGE

$(SHIFTLIGHT_DEBUG_M32R_LINKER03_OUTFILESC0) : $(SHIFTLIGHT_DEBUG_M32R_LINKER03_INFILESC0)
	$(SHIFTLIGHT_DEBUG_M32R_C_COMPILER01_EXE) @<<
-g 
-MAP ..\ShiftLight\Debug\ShiftLight.map 
-o ..\ShiftLight\Debug\ShiftLight.abs 
-SEC PARAMS=05B000,SHIFTLIGHTCODE=05B050 
..\ShiftLight\Debug\start.mo 
..\ShiftLight\Debug\ShiftLight.mo
<<

!MESSAGE
!MESSAGE Executing Renesas M32R Stype Converter04 phase
!MESSAGE

$(SHIFTLIGHT_DEBUG_M32R_LOAD_MODULE_CONVERTER04_OUTFILESC0) : $(SHIFTLIGHT_DEBUG_M32R_LINKER03_OUTFILESC0)
	$(SHIFTLIGHT_DEBUG_M32R_LOAD_MODULE_CONVERTER04_EXE) @<<
-o ..\ShiftLight\Debug\ShiftLight.mot 
..\ShiftLight\Debug\ShiftLight.abs
<<

